kind: BuildConfig
apiVersion: build.openshift.io/v1
metadata:
  name: httpd-custom-build
  labels:
    name: httpd-custom-build
  annotations:
    template.alpha.openshift.io/wait-for-ready: 'true'
spec:
  strategy:
    type: Custom
    customStrategy:
      forcePull: true
      from:
        kind: ImageStreamTag
        name: custom-builder-image:1.0
        namespace: source-test
  output:
    to:
      kind: ImageStreamTag
      name: httpd-custom:1.0